# Generated by Django 5.0.3 on 2024-03-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('trainID', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('n', models.IntegerField(max_length=6)),
                ('heure', models.CharField(max_length=5)),
                ('destination', models.CharField(max_length=30)),
                ('voie', models.IntegerField(max_length=6)),
            ],
        ),
    ]
